### ISSUE TITLE
App.js test not passing

### ISSUE THREAD

**Issue by muZk** [expo/new-project-template#10]
Hello! I cloned this repo and ran:

```
yarn
yarn run test
```

But got the following error: `TypeError: TaskQueue: Error with task : Cannot read property 'Object.<anonymous>' of null`

Thoughts?

**Comment by brentvatne** [comment]
just ran it on master and works as expected for sdk28

**Comment by brentvatne** [comment]
if you still encounter this error on master then you can try one of the solutions in https://github.com/facebook/jest/issues/4710
