### ISSUE TITLE
Provide .flowconfig as part of new project template

### ISSUE THREAD

**Issue by bolinfest** [expo/new-project-template#2]
I'm trying to create a proper `.flowconfig` for the starter project myself. I'm a bit confused. Here's what I'm trying right now:

```
[ignore]
# Nuclide does this, so perhaps I do, too?
.*/node_modules/fbjs/lib/.*

[libs]
./lib/fixit.js
./node_modules/react-native/Libraries/react-native/react-native-interface.js

[options]
esproposal.decorators=ignore
esproposal.export_star_as=enable
unsafe.enable_getters_and_setters=true

suppress_comment=.*\\$FlowFixMe.*
suppress_comment=.*\\$FlowIssue.*
suppress_comment=.*\\$FlowIgnore.*

[version]
0.32.0
```

Unfortunately, this has tons of errors, including things like:

```
node_modules/react-native/Libraries/Animated/src/AnimatedWeb.js:13
 13: var AnimatedImplementation = require('AnimatedImplementation');
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AnimatedImplementation. Required module not found
```

However, I believe `AnimatedImplementation` is there and is declared correctly, but it is under `react-native`, which uses `module.system=haste` whereas the default Exponent app does not (which is what I would prefer).

Is the issue that `module.system=haste` and `module.system=node` cannot be used in the same tree of dependencies? I'm pretty sure that's not the case, though I'm also unsure of how to fix this.

**Comment by bolinfest** [comment]
Hmm, practically speaking, apparently all React Native apps have to specify:

```
[options]
module.system=haste
```

**Comment by wli** [comment]
@bolinfest I did some work on this - see https://github.com/exponentjs/new-project-template/pull/3

You have to specify version Flow v0.30.0, since that's what exponent SDK 10 is locked to (via react-native).

**Comment by dikaiosune** [comment]
@bolinfest CRNA now has a [.flowconfig](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/.flowconfig) that works with Expo, and we should probably bring that into the template projects at some point soon (cc @brentvatne).

**Comment by brentvatne** [comment]
flow and react-native (outside of fb) is a bit of a mess still... eg: https://github.com/facebook/react-native/issues/15145

if someone builds and maintains a react-native flow interface then I would love to include first class support for it, but otherwise it's kind of up to each person to figure out what works right now, I don't have the time or expertise in flow to handle it

**Comment by brentvatne** [comment]
https://expo.canny.io/feature-requests/p/built-in-support-for-flow
