### ISSUE TITLE
Error after expo-sdk upgrade from 18 to 20

### ISSUE THREAD

**Issue by vyemialyanchyk** [expo/new-project-template#6]
after these changes:
app.json:
`
{
  "expo": {
    "sdkVersion": "18.0.0",
...
`
==>
`
{
  "expo": {
    "sdkVersion": "20.0.0",
...
`

package.json:
`
	"devDependencies": {
		"jest-expo": "18.0.0",
		"jest-expo-ts": "18.0.1",
...
	"dependencies": {
		"expo": "18.0.0",
		"react-native": "0.45.1",
...

`
==>
`
	"devDependencies": {
		"jest-expo": "20.0.0",
		"jest-expo-ts": "20.0.0",
...
	"dependencies": {
		"expo": "20.0.0",
		"react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
...

`

gets error with

>npm start

> react-native-scripts start

4:27:29 PM: Starting packager...
***ERROR STARTING PACKAGER***
Starting React Native packager...
Scanning 779 folders for symlinks in .......\node_modules (17ms)

EISDIR: illegal operation on a directory, read
4:33:49 PM: Stopping packager...
4:33:49 PM: Packager stopped.

**Comment by dikaiosune** [comment]
Hi! Can you remove node_modules, reinstall them, and if you're still having problems create this issue on the https://github.com/react-community/create-react-native-app repository? Thanks!

**Comment by vyemialyanchyk** [comment]
Hi! I do not sure these are related. Yes, I did create initial project with create-react-native-app and update this to be workable with TS, but it is workable till upgrade to expo/jest-expo/jest-expo-ts. I did upgrade according new-project-template, new-project-template is not runable with 
npm start
to reproduce the problem, but looks like it should be reproducible...

**Comment by vyemialyanchyk** [comment]
I did remove node_modules plenty of times and reinstall, it does not help..
